services:
  backend:
    container_name: fastapi-adneura-backend
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    networks:
      - adneura-net
    command: fastapi dev main.py --host 0.0.0.0 --port 8000

  celery_worker:
    build:
      dockerfile: Dockerfile
    container_name: fastapi-celery-worker
    command: celery -A core.celery_worker worker --loglevel=info --concurrency=7
    volumes:
      - .:/app
    depends_on:
      - backend
    env_file:
      - .env.dev
    networks:
      - adneura-net

  flower:
    build:
      dockerfile: Dockerfile
    container_name: fastapi-flower
    command: celery -A core.celery_worker flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - celery_worker
    networks:
      - adneura-net
  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adneura-net
  
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - adneura-net

volumes:
  postgres_data:
  redis_data:

networks:
  adneura-net:
