# Generated by Django 5.1.3 on 2024-11-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='BrandAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('step', models.CharField(choices=[('about', 'About'), ('key_characteristics', 'Key Characteristics'), ('category', 'Category'), ('positioning', 'Positioning'), ('target_audience', 'Target Audience'), ('key_competitors', 'Key Competitors'), ('done', 'Done')], default='about', max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_analyses', to='api.user')),
            ],
            options={
                'db_table': 'brand_analyses',
            },
        ),
    ]
