# Generated by Django 5.1.4 on 2025-02-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_strategicgoals'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicgoals',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
