# Generated by Django 5.1.3 on 2024-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_table_brandinfo_delete_brandanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandinfo',
            name='history',
            field=models.JSONField(default=list),
        ),
    ]
