# Generated by Django 5.1.4 on 2025-02-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_strategicgoals_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='key_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
