# Generated by Django 5.1.3 on 2024-12-05 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_brandinfo_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True)),
                ('themes', models.TextField(blank=True, null=True)),
                ('messaging', models.TextField(blank=True, null=True)),
                ('style', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='brandinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='brandinfo',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='brandinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brandinfo',
            name='history',
        ),
        migrations.RemoveField(
            model_name='brandinfo',
            name='updated_at',
        ),
        migrations.AlterModelTable(
            name='brandinfo',
            table=None,
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_legacy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='api.advertisinglegacy')),
                ('brand_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='api.brandinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('psycho_graphic', models.TextField(blank=True, null=True)),
                ('attitudinal', models.TextField(blank=True, null=True)),
                ('self_concept', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='api.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.JSONField(blank=True, null=True)),
                ('age_bracket', models.CharField(blank=True, choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('64+', '64+')], max_length=50, null=True)),
                ('hhi', models.CharField(blank=True, choices=[('<75k', '<75k'), ('75k-100k', '75k-100k'), ('100k-150k', '100k-150k'), ('150k-250k', '150k-250k'), ('>250k', '>250k')], max_length=50, null=True)),
                ('race', models.JSONField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('audience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='api.audience')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('why_it_resonates', models.TextField(blank=True, null=True)),
                ('scene_description', models.TextField(blank=True, null=True)),
                ('brand_sense_sight', models.JSONField(blank=True, null=True)),
                ('brand_sense_sound', models.JSONField(blank=True, null=True)),
                ('brand_sense_smell', models.TextField(blank=True, null=True)),
                ('brand_sense_taste', models.TextField(blank=True, null=True)),
                ('brand_sense_touch', models.TextField(blank=True, null=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='api.audience')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
