# Generated by Django 5.1.4 on 2025-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_audience_key_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='audience_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
