# Generated by Django 5.1.6 on 2025-03-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_brand_audience_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='territory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
