# Generated by Django 5.1.6 on 2025-03-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_brand_brand_universe_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='ad_legacy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='api.advertisinglegacy'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='api.brandinfo'),
        ),
    ]
