# Generated by Django 5.1.3 on 2024-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='trigger_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
