# Generated by Django 5.1.6 on 2025-04-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_brand_ad_legacy_alter_brand_brand_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='informations_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
