# Generated by Django 5.1.4 on 2024-12-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_trigger_trigger_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='audience_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
