# Generated by Django 5.1.4 on 2024-12-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_audience_brand_keywords_audience_general_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
