# Generated by Django 5.1.4 on 2025-01-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_demographics_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='brand_sense_smell',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='brand_sense_sight',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='brand_sense_sound',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='brand_sense_taste',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='brand_sense_touch',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='scene_description',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='why_it_resonates',
        ),
    ]
