# Generated by Django 5.1.4 on 2025-01-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_brand_sense_smell_trigger_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandinfo',
            name='first_access',
            field=models.BooleanField(default=False),
        ),
    ]
