# Generated by Django 5.1.4 on 2025-01-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_brandinfo_first_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
