# Generated by Django 5.1.4 on 2025-01-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_audience_image_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
