"""StrategicGoal and Campaign relationship

Revision ID: 8786bc693848
Revises: 8effffb1faea
Create Date: 2025-05-22 22:21:39.084177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8786bc693848"
down_revision: Union[str, None] = "8effffb1faea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategic_goals", sa.Column("campaign_id", sa.Uuid(), nullable=False)
    )
    op.drop_constraint(
        "strategic_goals_brand_id_fkey", "strategic_goals", type_="foreignkey"
    )
    op.create_foreign_key(None, "strategic_goals", "campaigns", ["campaign_id"], ["id"])
    op.drop_column("strategic_goals", "brand_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategic_goals",
        sa.Column("brand_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "strategic_goals", type_="foreignkey")
    op.create_foreign_key(
        "strategic_goals_brand_id_fkey",
        "strategic_goals",
        "brands",
        ["brand_id"],
        ["id"],
    )
    op.drop_column("strategic_goals", "campaign_id")
    # ### end Alembic commands ###
