"""atualizando db

Revision ID: 88e81e532645
Revises: 
Create Date: 2025-06-11 18:40:20.842572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '88e81e532645'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategic_goals', sa.Column(
        'strategic_goal_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('triggers', sa.Column(
        'strategic_goal_id', sa.UUID(), nullable=True))

    op.create_foreign_key(None, 'triggers', 'strategic_goals', [
                          'strategic_goal_id'], ['id'])
    op.drop_column('triggers', 'goal_color')
    op.drop_column('triggers', 'campaign_name')
    op.drop_column('triggers', 'goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triggers', sa.Column(
        'goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('triggers', sa.Column('campaign_name',
                  sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('triggers', sa.Column(
        'goal_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'triggers', type_='foreignkey')
    op.drop_column('triggers', 'strategic_goal_id')
    op.drop_column('strategic_goals', 'strategic_goal_color')
    # ### end Alembic commands ###
