"""update demographic model

Revision ID: 8effffb1faea
Revises: 
Create Date: 2025-05-17 19:36:54.538587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8effffb1faea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics', sa.Column(
        'ethnicity', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('demographics', 'race')
    op.add_column('strategic_goals', sa.Column(
        'is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategic_goals', 'is_active')
    op.add_column('demographics', sa.Column(
        'race', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('demographics', 'ethnicity')
    # ### end Alembic commands ###
