"""update trigger

Revision ID: d4cd25b97d8e
Revises: ee8589fc05cb
Create Date: 2025-05-28 21:38:35.377896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd4cd25b97d8e'
down_revision: Union[str, None] = 'ee8589fc05cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triggers', sa.Column(
        'goal_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triggers', 'goal_color')
    # ### end Alembic commands ###
