"""update column name target_audience to traditional_target_audience in brand

Revision ID: 6aebe69c4ee9
Revises: d4cd25b97d8e
Create Date: 2025-05-30 14:37:07.317073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6aebe69c4ee9'
down_revision: Union[str, None] = 'd4cd25b97d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('traditional_target_audience',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('brands', 'target_audience')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('target_audience',
                  sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('brands', 'traditional_target_audience')
    # ### end Alembic commands ###
